name: CommitHunter

on:
  push:                # Trigger on any push to any branch
  schedule:
    - cron: '0 0 * * *'  # Every 24 hours at 00:00 UTC
  workflow_dispatch:    # Manual trigger

jobs:
  scan:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run commit hunter
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          python commithunter.py

      - name: Commit results
        run: |
          git config user.name 'github-actions[bot]'
          git config user.email '41898282+github-actions[bot]@users.noreply.github.com'
          git add output/* || true
          if git diff --cached --quiet; then
              echo "No changes to commit."
            else
              git commit -m "chore: update commit hunter results"
              git push
  
