name: CommitHunter

on:
  push:
    branches: [ main, master ]
  schedule:
    - cron: '0 * * * *'  # Every hour at minute 0
  workflow_dispatch:    # Manual trigger

# Set the permissions for the GITHUB_TOKEN
permissions:
  contents: write
  security-events: read
  actions: read

jobs:
  scan:
    runs-on: ubuntu-latest
    
    # Use the GitHub token with the necessary permissions
    permissions:
      contents: write  # For committing changes
      security-events: read  # For reading security advisories
      actions: read  # For workflow status checks

    steps:
      - uses: actions/checkout@v4
        with:
          # Fetch all history for all branches and tags
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run commit hunter
        env:
          # Use the built-in GITHUB_TOKEN with the security-events: read permission
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          python commithunter.py

      - name: Commit and push changes
        if: github.ref == 'refs/heads/main' || github.ref == 'refs/heads/master'
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email '41898282+github-actions[bot]@users.noreply.github.com'
          
          # Add only the output directory and README
          git add README.md output/ || echo "No files to add"
          
          # Check if there are changes to commit
          if ! git diff --cached --quiet; then
            git commit -m "chore: update security findings [skip ci]"
            git push
          else
            echo "No changes to commit."
          fi
  
